version: '2'
services:
  zookeeper:
    image: izhar/zk
    hostname: zookeeper
  kafka:
    depends_on:
      - zookeeper
    build: .
    image: izhar/kafka
    hostname: kafka
    environment:
      ZKHOST: zookeeper
      ADVERTISED_PORT: 9092
      ADVERTISED_HOST: $HOSTNAME
      BROKERID: -1
