version: '2'
services:
  zookeeper:
    image: izhar/zookeeper
    hostname: zookeeper
  kafka:
    depends_on:
      - zookeeper
    build: .
    image: izhar/kafka_211
    environment:
      ZKHOST: zookeeper
      # auto generate broker ids
      BROKERID: -1
