version: '2'
services:
  zookeeper:
    image: izhar/zk
    hostname: zookeeper
  kafka:
    depends_on:
      - zookeeper
    build: .
    image: izhar/kafka08
    environment:
      ZKHOST: zookeeper
      BROKERID: 0
