version: '2'
services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
  kafka:
    depends_on:
      - zookeeper
    build: .
    image: kafka
    hostname: kafka
    environment:
      ZKHOST: zookeeper
      BROKERID: -1
